### ISSUE TITLE
java download fails, repo_server points to internal IP

### ISSUE THREAD

**Issue by muelli** [mcsrainbow/ansible-playbook-cdh5#1]
Right now, the role does not work because the repo_server variable points to 10.10.something.
This makes the java download fail.

Something like this works better for me:

```
 - name: download jdk-6u35-linux-x64-rpm.bin
-  get_url: url=http://{{ repo_server }}/repo/misc/jdk-6u45-linux-x64-rpm.bin dest=/root/deploy/hadoop/jdk-6u45-linux-x64-rpm.bin mode=0755
+  get_url: url=http://dev.h2cycle.com/java/6u45/jdk-6u45-linux-x64-rpm.bin  mode=0755   dest=/root/deploy/hadoop/jdk-6u45-linux-x64-rpm.bin sha256sum=f432ce7dbc4ff7c104d67a967e28078ec50e084d1934e579ba6c7d6038d76cf9

```

**Comment by ShylockGou** [comment]
```
- name: download jdk-8u101-linux-x64.rpm
  get_url:
    url:  'http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.rpm'
    dest: '/root/deploy/hadoop/jdk-8u101-linux-x64.rpm'
    headers: "Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'"
    validate_certs: "no"
    mode: '0755'
  tags:
  - cdh5-base
  - cdh5-jdk
```
